Controllers/ChefsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Chef_N__Dishes.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;


namespace Chef_N__Dishes.Controllers;

public class ChefsController : Controller
{
    private MyContext _context;

    public ChefsController(MyContext context)
    {
        _context = context;
    }

    [HttpGet("/chefs/new")]
    public IActionResult Index()
    {
        return View("Index");
    }

    [HttpGet("/")]
    public IActionResult AllChefs(){
        // Get all Chefs
        List<Chef> Chefs_Stats = _context.Chefs.Include(dish => dish.ChefDishes).ToList();
        return View("AllChefs", Chefs_Stats);
    }

    [HttpPost("/register")]
    public IActionResult Register(Chef newUser)
    {
        if(ModelState.IsValid){
            if(_context.Chefs.Any(u => u.Email == newUser.Email)){
                ModelState.AddModelError("Email", "is taken");
            }
        }else{
            return Index();
        }

        PasswordHasher<Chef> hashSlingingSlasher = new PasswordHasher<Chef>();
        newUser.Password = hashSlingingSlasher.HashPassword(newUser, newUser.Password);

        _context.Chefs.Add(newUser);
        _context.SaveChanges();

        HttpContext.Session.SetInt32("UUID", newUser.ChefId);
        HttpContext.Session.SetString("FirstName", newUser.FirstName);
        HttpContext.Session.SetString("LastName", newUser.LastName);
        HttpContext.Session.SetString("FullName", $"{newUser.FirstName} {newUser.LastName}");
        return RedirectToAction("AllChefs");
    }

    [HttpPost("/login")]
    public IActionResult Login(LoginUser loginUser)
    {
        if(!ModelState.IsValid){
            return Index();
        }

        Chef? dbUser = _context.Chefs.FirstOrDefault(u => u.Email == loginUser.LoginEmail); 

        if(dbUser == null){
            ModelState.AddModelError("LoginEmail", "invalid.");
            return Index();
        }

        PasswordHasher<LoginUser> hashSlingingSlasher = new PasswordHasher<LoginUser>();
        PasswordVerificationResult pwCompareResult = hashSlingingSlasher.VerifyHashedPassword(loginUser, dbUser.Password, loginUser.LoginPassword);

        
        if(pwCompareResult == 0){
            ModelState.AddModelError("LoginPassword", "invalid.");
            return Index();
        }

        HttpContext.Session.SetInt32("UUID", dbUser.ChefId);
        HttpContext.Session.SetString("FirstName", dbUser.FirstName);
        HttpContext.Session.SetString("LastName", dbUser.LastName);
        HttpContext.Session.SetString("FullName", $"{dbUser.FirstName} {dbUser.LastName}");
        return RedirectToAction("AllChefs");
    }

    [HttpPost("/logout")]
    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return RedirectToAction("Index");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chefs N' Dishes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Chef_N__Dishes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Chefs N' Dishes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chefs" asp-action="Index">Home</a>
                        </li>
                        @if (Context.Session.GetInt32("UUID") != null)
                        {
                            <li class="nav-item">
                                <form asp-controller="Chefs" asp-action="Logout" method="post">
                                    <button class="btn btn-link">
                                        Logout @Context.Session.GetString("FirstName") @Context.Session.GetInt32("UUID")
                                    </button>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Chefs N' Dishes
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>