Models/Dish.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
public class Dish
{
    [Key]
    public int DishId {get; set;}

    [Required]
    public int ChefId {get; set;}
    
    public Chef? ChefName {get; set;}

    [Required]
    [Display(Name = "Dish's Name")]
    [MaxLength(45)]
    public string DishName {get; set;}

    [Required]
    [Display(Name = "Calories")]
    [Range(1, 99999)]
    public int Calories {get; set;}

    [Required]
    [Display(Name = "Tastiness")]
    [Range(1, 5)]
    public int Tastiness {get; set;}

    // [Display(Name = "Description")]
    // [MinLength(20)]
    // public string? Description {get; set;}

    public DateTime CreatedAt {get; set;} = DateTime.Now;
    public DateTime UpdatedAt {get; set;} = DateTime.Now;
}

Controllers/DishesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Chef_N__Dishes.Models;
using Microsoft.EntityFrameworkCore;

namespace CRUDelicious.Controllers;

public class DishesController : Controller
{
    private int? uid
    {
        get{
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    private bool loggedIn
    {
        get{
            return uid != null;
        }
    }
    private MyContext _context;

    public DishesController(MyContext context)
    {
        _context = context;
    }
    
    [HttpGet("/dishes")]
    public IActionResult AllDishes(){
        // if(!loggedIn){
        //     return RedirectToAction("Index", "Chefs");
        // }

        // Get all Dishes
        List<Dish> All_Dishes = _context.Dishes.Include(pain => pain.ChefName).ToList();
        ViewBag.Pain = _context.Chefs.ToList();
        return View("AllDishes", All_Dishes);
    }

    [HttpGet("/dishes/new")]
    public IActionResult New(){
        if(!loggedIn){
            return RedirectToAction("Index", "Chefs");
        }
        return View();
    }

    [HttpPost("/dishes/new")]
    public IActionResult CreateDish(Dish newDish)
    {
        if(!loggedIn){
            return RedirectToAction("Index", "Chefs");
        }

        if(ModelState.IsValid){
            Chef? AddDish = _context.Chefs.FirstOrDefault(d => d.ChefId == newDish.ChefId);
            // if(AddDish == null){
            //     return View("New");
            // }
            AddDish.ChefDishes.Add(newDish);


            // We can take the Dish object created from a form submission
            // And pass this object to the .Add() method
            _context.Dishes.Add(newDish);
            // OR _context.Dishes.Add(newDish);
            _context.SaveChanges();
            // Other code
            return View("AllDishes");
        }
        //return RedirectToAction("New");
        return View("New");
    }

    // [HttpGet("/dishes/{DishId}")]
    // public IActionResult One(int DishId)
    // {
    //     if(!loggedIn){
    //         return RedirectToAction("Index", "Chefs");
    //     }
        
    //     Dish? oneDish = _context.Dishes.FirstOrDefault(dish => dish.DishId == DishId);
    //     // Other code
    //     if(oneDish == null){
    //         return View("AllDishes");
    //     }
    //     return View("One", oneDish);
    // }

    // [HttpGet("/dishes/{DishId}/edit")]
    // public IActionResult Update(int DishId){
    //     if(!loggedIn){
    //         return RedirectToAction("Index", "Chefs");
    //     }

    //     Dish? editDish = _context.Dishes.FirstOrDefault(dish => dish.DishId == DishId);
    //     // Other code
    //     if(editDish == null){
    //         return View("AllDishes");
    //     }
    //     return View("Update", editDish);
    // }

    // [HttpPost("/dishes/{DishId}/edit")]
    // public IActionResult UpdateDish(int DishId, Dish editedDish)
    // {
    //     if(!loggedIn){
    //         return RedirectToAction("Index", "Chefs");
    //     }

    //     if(ModelState.IsValid){
    //         // We must first Query for a single Dish from our Context object to track changes.
    //         Dish RetrievedDish = _context.Dishes
    //             .FirstOrDefault(Dish => Dish.DishId == DishId);

    //         // Then we may modify properties of this tracked model object
    //         RetrievedDish.ChefName = editedDish.ChefName;
    //         RetrievedDish.DishName = editedDish.DishName;
    //         RetrievedDish.Calories = editedDish.Calories;
    //         RetrievedDish.Tastiness = editedDish.Tastiness;
    //         //RetrievedDish.Description = editedDish.Description;
    //         RetrievedDish.UpdatedAt = DateTime.Now;
            
    //         // Finally, .SaveChanges() will update the DB with these new values
    //         _context.SaveChanges();
            
    //         // Other code
    //         return RedirectToAction("AllDishes");
    //     }
    //     return View("Update", DishId);
    // }

    // [HttpGet("delete/{DishId}")]
    // public IActionResult DeleteDish(int DishId)
    // {
    //     if(!loggedIn){
    //         return RedirectToAction("Index", "Chefs");
    //     }

    //     // Like Update, we will need to query for a single Dish from our Context object
    //     Dish RetrievedDish = _context.Dishes
    //         .SingleOrDefault(Dish => Dish.DishId == DishId);
        
    //     // Then pass the object we queried for to .Remove() on Dishs
    //     _context.Dishes.Remove(RetrievedDish);
        
    //     // Finally, .SaveChanges() will remove the corresponding row representing this Dish from DB 
    //     _context.SaveChanges();
    //     // Other code
    //     return RedirectToAction("AllDishes");
    // }
}

Views/Dishes/AllDishes.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<Dish>


<div class="container text-center px-2">
    <h1 class="display-4"></h1>
    <h3><a href="/">Chefs</a>  |  Dishes  |  <a href="/chefs/new">Add a Chef</a>  |  <a href="/dishes/new">Add a Dish</a></h3>
    <div class="mt-5">
        <h2>Check out some recent dishes</h2>
        <hr width="100%"/><br/>
        <table class="card bg-light">
            <thead>
                <tr class="d-flex justify-content-around">
                    <td class="w-25">Name</td>
                    <td class="bg-secondary w-25">Chef</td>
                    <td class="w-25">Tastiness</td>
                    <td class="bg-secondary w-25">Calories</td>
                </tr>
            </thead>
            @foreach(Dish dish in Model){
                <tr class="d-flex justify-content-around">
                    <td class="w-25">@dish.DishName</td>
                    <td class="bg-secondary w-25">@dish.ChefName.FirstName @dish.ChefName.LastName</td>
                    <td class="w-25">@dish.Tastiness</td>
                    <td class="bg-secondary w-25">@dish.Calories</td>
                </tr>
            }
        </table>
    
    </div>
</div>

Views/Dishes/New.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model Dish; 

<div class="container text-center px-5">
    <h3><a href="/">Chefs</a>  |  <a href="/dishes">Dishes</a>  |  <a href="/chefs/new">Add a Chef</a>  |  Add a Dish</h3>
    <h1 class="display-4">Add a new Dish!</h1>
    <hr>
    <form class="form-group d-flex justify-content-between m-5" asp-action="CreateDish" asp-controller="Dishes" method="post">
        <div class="d-flex flex-column justify-content-between mx-2 ">
            @{
                var ID = Context.Session.GetInt32("UUID");
                // var Name = Context.Session.GetString("FullName");
            }
            <input type="hidden" asp-for="ChefId" value=@ID>
            @* <input type="hidden" asp-for="ChefName" value=@Name> *@

            <label asp-for="DishName"></label>
            <input asp-for="DishName">
            <span asp-validation-for="DishName" class="text-danger"></span>
            <br>
            <label asp-for="Calories"></label>
            <input asp-for="Calories">
            <span asp-validation-for="Calories" class="text-danger"></span>
            <br>
        </div>
        <div class="d-flex flex-column justify-content-start mx-2">
            <label asp-for="Tastiness"></label>
            <input asp-for="Tastiness">
            <span asp-validation-for="Tastiness" class="text-danger"></span>
            <button class="btn btn-secondary mt-3" type="submit">Add Dish</button>
        </div>
        @* <div class="d-flex flex-column justify-content-start mx-2">
            <label asp-for="Description"></label>
            <input asp-for="Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div> *@
    </form>
</div>

Views/Dishes/One.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model Dish; 
<div class="container text-center d-flex flex-column justify-content-center">
    <h1 class="display-4">@Model.DishName</h1>
    <h3><a href="/dashboard">Home</a>  |  <a href="/dishes/new">Add a Dish</a></h3>
    
    <fieldset class="card bg-light w-50 mt-5 px-5 pt-3">
        <legend>@Model.DishName by @Model.ChefName</legend>
        <hr width="100%">
        @* <span class="d-flex justify-content-between mx-5">
            <p>@Model.Description</p>
        </span> *@
        <span class="d-flex justify-content-between mx-5">
            <p>Calories: @Model.Calories</p>
        </span>
        <span class="d-flex justify-content-between mx-5">
            <p>Tastiness: @Model.Tastiness</p>
        </span>
        <span class="d-flex justify-content-between mx-5">
            <a asp-action="DeleteDish" asp-controller="Dishes" asp-route-DishId="@Model.DishId" class="btn btn-danger my-3">Delete</a>
            <a asp-action="Update" asp-controller="Dishes" asp-route-DishId="@Model.DishId" class="btn btn-primary px-4 my-3">Edit</a>
        </span>
    </fieldset>
</div>

Views/Dishes/Update.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model Dish; 

<div class="container text-center px-5">
    <h1 class="display-4">Edit @Model.DishName</h1>
    <h3><a href="/dashboard">Home</a>  |  <a href="/dishes/new">Add a Dish</a></h3>
    <form class="form-group d-flex justify-content-between m-3" asp-action="UpdateDish" asp-controller="Dishes" asp-route-DishId="@Model.DishId" method="post">
        <div class="d-flex flex-column justify-content-between mx-2">
            <label asp-for="ChefName"></label>
            <input asp-for="ChefName" value="@Model.ChefName">
            <span asp-validation-for="ChefName" class="text-danger"></span>
            <label asp-for="DishName"></label>
            <input asp-for="DishName" value="@Model.DishName">
            <span asp-validation-for="DishName" class="text-danger"></span>
            <label asp-for="Calories"></label>
            <input asp-for="Calories" value="@Model.Calories">
            <span asp-validation-for="Calories" class="text-danger"></span>
        </div>
        <div class="d-flex flex-column justify-content-start mx-2">
            <label asp-for="Tastiness"></label>
            <input asp-for="Tastiness" value="@Model.Tastiness">
            <span asp-validation-for="Tastiness" class="text-danger"></span>
            <button class="btn btn-secondary mt-3" type="submit">Edit Dish</button>
        </div>
        @* <div class="d-flex flex-column justify-content-start mx-2">
            <label asp-for="Description"></label>
            <input asp-for="Description" value="@Model.Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div> *@
    </form>
</div>